version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: digilinq/platform/user-service
    container_name: user-service
    networks:
      - digilinq-network
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "8001:80"
networks:
  digilinq-network:
    name: digilinq
    external: true